### PR TITLE
Cease and desist

### PR DESCRIPTION
**Pull request by ghost**
Please remove the incompatible files listed below by merging this pull request.
The way the 3 files below are licensed does not permit their use on the site http://uc.rosedu.org/

```
synchronize_statistics.py
js/main.js
en/js/main.js
```

### CODE REVIEW

**Comment by mihaimaruseac** [comment]
We will merge this pull request on 15th of September when the current contracts signed before licensing issues emerged reach their end-of-life.

**Comment by mihaimaruseac** [comment]
As agreed via email, we will postpone the merge date to 1st of October.

**Comment by valenting** [comment]
This pretty much crippled the uc.rosedu.org website

**Comment by vilie** [comment]
I will build and push a static html version of the website (snapshot) to the past-editions/2014 directory.

As for the index, a simple page pointing to the past editions should be fine.

**Comment by vilie** [comment]
Hello,

Until I find a permanent fix I will remove the logos and add the files back.

I think that is OK to everyone.

**Comment by ghost** [comment]
You need to read the entire e-mail thread that led to the agreement hinted at by @mihaimaruseac above.
I thought everything had settled down when this pull request was merged.
Do you really want to reignite this?

**Pull request merged**
